name: Storybook - Deploy Application to Amazon S3
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
concurrency: storybook_deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read .pnpmversion file
        id: read_pnpm_version
        run: echo "PNPM_VERSION=$(cat .pnpmversion)" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: |
          pnpm nx build-storybook web --no-cloud

      - name: Archive Stage storybook Build Execution Result
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-storybook
          path: apps/web/storybook-static
  stage_deployment:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AMPLIFIDEV_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_AMPLIFIDEV_SECRET_KEY }}
      AWS_REGION: 'us-west-2'
      STORYBOOK_BUCKET_NAME: library-stage.pattern.com
      SB_SITE_CF_ID: EZVJRH04PCNSV
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-storybook
          path: storybook-static

      - name: Deploy storybook app
        env:
          FOLDER: storybook-static
        run: aws s3 sync ./$FOLDER s3://$STORYBOOK_BUCKET_NAME/pxm --delete

  production_deployment:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: stage_deployment
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AMPLIFIPROD_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_AMPLIFIPROD_SECRET_KEY }}
      AWS_REGION: 'us-west-2'
      STORYBOOK_BUCKET_NAME: library.pattern.com
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-storybook
          path: storybook-static

      - name: Deploy storybook app
        env:
          FOLDER: storybook-static
        run: aws s3 sync ./$FOLDER s3://$STORYBOOK_BUCKET_NAME/pxm --delete
